## **Tasks**

1.Create an array named a_small_one with dimensions 8x8 and values 1, 2, ..., 64.

In [2]:
# Solutions for tasks 1-9
import numpy as np
import timeit

# 1) 8x8 array with values 1..64
a_small_one = np.arange(1, 65).reshape(8, 8)
print("a_small_one:\n", a_small_one)

a_small_one:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


2.For the array a_small_one, calculate:

* the sum for each column,
* the cumulative sum for each row,
* the average value for each row,

In [3]:
# 2) Basic calculations on a_small_one
sum_each_column = a_small_one.sum(axis=0)
cumsum_each_row = a_small_one.cumsum(axis=1)
avg_each_row = a_small_one.mean(axis=1)

print("\nSum for each column:\n", sum_each_column)
print("\nCumulative sum for each row:\n", cumsum_each_row)
print("\nAverage value for each row:\n", avg_each_row)


Sum for each column:
 [232 240 248 256 264 272 280 288]

Cumulative sum for each row:
 [[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]

Average value for each row:
 [ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


3.Return a subarray from the array a_small_one containing even-numbered elements (do not overwrite this variable).

In [4]:
# 3) Subarray with even elements (without overwriting a_small_one)
even_subarray = a_small_one[a_small_one % 2 == 0]
print("\nEven elements subarray:\n", even_subarray)


Even elements subarray:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64]


4.Save the array a_small_one to a variable named no_even_small_one, replacing even values with a value such as nan.



In [5]:
# 4) Replace even values with nan in a copy
no_even_small_one = a_small_one.astype(float).copy()
no_even_small_one[no_even_small_one % 2 == 0] = np.nan
print("\nno_even_small_one (even -> nan):\n", no_even_small_one)


no_even_small_one (even -> nan):
 [[ 1. nan  3. nan  5. nan  7. nan]
 [ 9. nan 11. nan 13. nan 15. nan]
 [17. nan 19. nan 21. nan 23. nan]
 [25. nan 27. nan 29. nan 31. nan]
 [33. nan 35. nan 37. nan 39. nan]
 [41. nan 43. nan 45. nan 47. nan]
 [49. nan 51. nan 53. nan 55. nan]
 [57. nan 59. nan 61. nan 63. nan]]


5.For the array no_even_small_one, calculate the following using functions that handle nan values (these functions usually have the prefix nan):

* the sum for each row,
* the average for each column,
* the smallest value in the entire array,

In [6]:
# 5) NaN-aware calculations
nan_sum_each_row = np.nansum(no_even_small_one, axis=1)
nan_avg_each_column = np.nanmean(no_even_small_one, axis=0)
nan_min_all = np.nanmin(no_even_small_one)

print("\nNaN-aware row sums:\n", nan_sum_each_row)
print("\nNaN-aware column means:\n", nan_avg_each_column)
print("\nNaN-aware minimum value in array:\n", nan_min_all)


NaN-aware row sums:
 [ 16.  48.  80. 112. 144. 176. 208. 240.]

NaN-aware column means:
 [29. nan 31. nan 33. nan 35. nan]

NaN-aware minimum value in array:
 1.0


/tmp/ipykernel_6803/121339227.py:3: RuntimeWarning: Mean of empty slice
  nan_avg_each_column = np.nanmean(no_even_small_one, axis=0)


6.Insert the following into the no_even_small_one array using the np.where function:

* the value 1 for each np.nan value (see the built-in np.isnan() function)
* even numbers, which we previously replaced with nan values (now 1 if the first step is completed), so we restore the array to its original state from the a_small_one array—for the condition, insert the value from a_small_one or no_even_small_one

In [7]:
# 6) Use np.where:
#    a) replace each nan by 1
no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
print("\nAfter replacing nan with 1:\n", no_even_small_one)

#    b) restore original even numbers from a_small_one
#       (positions that were set to 1 correspond to former even values)
no_even_small_one = np.where(no_even_small_one == 1, a_small_one, no_even_small_one)
print("\nAfter restoring even numbers:\n", no_even_small_one)


After replacing nan with 1:
 [[ 1.  1.  3.  1.  5.  1.  7.  1.]
 [ 9.  1. 11.  1. 13.  1. 15.  1.]
 [17.  1. 19.  1. 21.  1. 23.  1.]
 [25.  1. 27.  1. 29.  1. 31.  1.]
 [33.  1. 35.  1. 37.  1. 39.  1.]
 [41.  1. 43.  1. 45.  1. 47.  1.]
 [49.  1. 51.  1. 53.  1. 55.  1.]
 [57.  1. 59.  1. 61.  1. 63.  1.]]

After restoring even numbers:
 [[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


7.Create an array named normal_100 with dimensions 100x100 by sampling values from a standard normal distribution using a np.random module.

In [10]:
# 7) 100x100 array from standard normal distribution
rng = np.random.default_rng()
normal_100 = rng.standard_normal((100, 100))

8.For the normal_100 array, calculate:

* the mean value in each row and column (separately),
* calculate the average absolute difference for the values in the previous point relative to the value 0 (this is the expected value given our assumptions about the normal distribution) — separately for the column averages and the row averages; keep in mind that operations on a NumPy array are performed in broadcast mode.

In [11]:
# 8) Means and average absolute difference from 0
row_means = normal_100.mean(axis=1)
col_means = normal_100.mean(axis=0)

avg_abs_diff_row_means = np.mean(np.abs(row_means - 0))
avg_abs_diff_col_means = np.mean(np.abs(col_means - 0))

print("\nnormal_100 row means (first 10):\n", row_means[:10])
print("\nnormal_100 column means (first 10):\n", col_means[:10])
print("\nAverage absolute difference from 0 (row means):", avg_abs_diff_row_means)
print("Average absolute difference from 0 (column means):", avg_abs_diff_col_means)


normal_100 row means (first 10):
 [-0.07326772  0.01565561  0.02128589  0.07809526 -0.19148596  0.183933
 -0.15816758 -0.00854764 -0.04459822 -0.08819243]

normal_100 column means (first 10):
 [ 2.79122382e-02 -1.49699850e-01  4.04508692e-02  4.02810550e-02
 -1.05056073e-01  4.69640835e-06  3.77005228e-02 -4.10031345e-02
  1.16380379e-01  5.46331748e-02]

Average absolute difference from 0 (row means): 0.073283623127721
Average absolute difference from 0 (column means): 0.07724667674580003


9. Create a 1000x1000 array by filling it with random values from a standard normal distribution, and then, using examples from previous labs (the timeit module), compare the execution times for this array:

* writing to a text file vs. writing to a file in pickle format vs. writing to a compressed file (the savez_compressed function in the NumPy library documentation)
* reading arrays back from the three files mentioned above.

In [12]:
# 9) Time comparison for save/load methods on a 1000x1000 normal array
big_normal = rng.standard_normal((1000, 1000))

# Save methods
save_txt_time = timeit.timeit(
    stmt="np.savetxt('big_normal.txt', big_normal)",
    globals=globals(),
    number=1,
)

save_npy_time = timeit.timeit(
    stmt="np.save('big_normal.npy', big_normal)",
    globals=globals(),
    number=3,
)

save_npz_time = timeit.timeit(
    stmt="np.savez_compressed('big_normal_compressed.npz', big_normal)",
    globals=globals(),
    number=3,
)

# Load methods
load_txt_time = timeit.timeit(
    stmt="_ = np.loadtxt('big_normal.txt')",
    globals=globals(),
    number=1,
)

load_npy_time = timeit.timeit(
    stmt="_ = np.load('big_normal.npy')",
    globals=globals(),
    number=10,
)

load_npz_time = timeit.timeit(
    stmt="_ = np.load('big_normal_compressed.npz')['arr_0']",
    globals=globals(),
    number=10,
)

print("\n--- Time comparison (seconds) ---")
print(f"Save TXT (1 run): {save_txt_time:.4f}")
print(f"Save NPY (3 runs): {save_npy_time:.4f}")
print(f"Save NPZ compressed (3 runs): {save_npz_time:.4f}")
print(f"Load TXT (1 run): {load_txt_time:.4f}")
print(f"Load NPY (10 runs): {load_npy_time:.4f}")
print(f"Load NPZ compressed (10 runs): {load_npz_time:.4f}")


--- Time comparison (seconds) ---
Save TXT (1 run): 1.1233
Save NPY (3 runs): 0.0289
Save NPZ compressed (3 runs): 1.4111
Load TXT (1 run): 0.4874
Load NPY (10 runs): 0.0381
Load NPZ compressed (10 runs): 0.5989
