 **Task 1**

In [1]:
import numpy as np

# Creating the array 2, 4, 6... 32
# np.arange(start, stop, step) -> stop is exclusive, so we use 34
task1_arr = np.arange(2, 34, 2).reshape(4, 4)

print("Array:\n", task1_arr)
print("Data Type:", task1_arr.dtype)
print("Number of elements:", task1_arr.size)
print("Size of one element (bytes):", task1_arr.itemsize)
print("Memory allocated (nbytes):", task1_arr.nbytes)

Array:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Data Type: int64
Number of elements: 16
Size of one element (bytes): 8
Memory allocated (nbytes): 128


**Task 2**

In [2]:
# Create the converted array
task2_arr = task1_arr.astype(np.uint8)

# Check if it shares memory (base)
is_view = task2_arr.base is not None

print(f"Is it a view? {is_view}") # Should be False
print("New element size:", task2_arr.itemsize)
print("New total memory:", task2_arr.nbytes)

Is it a view? False
New element size: 1
New total memory: 16


**Task 3**

In [7]:
import numpy as np

# Helper functions provided in the lab to check memory sharing
def get_data_base(x):
    """ get a base of a given array """
    base = x
    while isinstance(base.base, np.ndarray):
        base = base.base
    return base

def arrays_share_data(x, y):
    """ compare object's identity to see if they share the same memory block """
    return get_data_base(x) is get_data_base(y)

# Task 3: Cutting out the 2x2 center (values 12, 14, 20, 22)
# The center values in your (4,4) array are at rows 1-2 and columns 1-2

# 1. Create a VIEW using basic slicing
# Slicing 1:3 gets index 1 and 2
view_center = task1_arr[1:3, 1:3]

# 2. Create a COPY using the .copy() method
copy_center = task1_arr[1:3, 1:3].copy()

# --- Verification ---
print("--- Task 3 Results ---")
print("Center View:\n", view_center)
print("Center Copy:\n", copy_center)

print("\nDoes the VIEW share data with the original array?", arrays_share_data(view_center, task1_arr))
print("Does the COPY share data with the original array?", arrays_share_data(copy_center, task1_arr))

# Additional check using the .base attribute
print("\nView base (should not be None):", "Shared" if view_center.base is not None else "None")
print("Copy base (should be None):", "Shared" if copy_center.base is not None else "None")

--- Task 3 Results ---
Center View:
 [[12 14]
 [20 22]]
Center Copy:
 [[12 14]
 [20 22]]

Does the VIEW share data with the original array? True
Does the COPY share data with the original array? False

View base (should not be None): Shared
Copy base (should be None): None


**Task 4**

In [4]:
# Create rows [1, 2, 3, 4] repeated 4 times
row = np.array([1, 2, 3, 4])
matrix_4x4 = np.tile(row, (4, 1))

# Mirror it horizontally using slicing [:, ::-1]
mirror = matrix_4x4[:, ::-1]

# Concatenate horizontally (axis=1)
task4_result = np.concatenate((matrix_4x4, mirror), axis=1)

print("Mirrored Array:\n", task4_result)

Mirrored Array:
 [[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


**Task 5**

In [5]:
Z_5 = np.ones((2, 2))

# Create the 4 blocks
b1 = Z_5 * 1
b2 = Z_5 * 2
b3 = Z_5 * 3
b4 = Z_5 * 4

# Combine them
top = np.hstack((b1, b2))    # Results in [[1,1,2,2],[1,1,2,2]]
bottom = np.hstack((b3, b4)) # Results in [[3,3,4,4],[3,3,4,4]]
final_matrix = np.vstack((top, bottom))

print("Final Matrix:\n", final_matrix)

Final Matrix:
 [[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
